export const industryRiskNames: string[] = [
   'Accidente Aereo',
   'Fallos del Software de Aplicación',
   'Accidente Automovilistico',
   'Ataque de Agente Biológico',
   'Ataque de Bomba',
   'Amenaza de Bomba ',
   'Derrame Químico',
   'Huelgas o Desordenes Civiles',
   'Crimen Computacional',
   'Falla/malfuncionamiento del CPU',
   'Ataques de DDoS or DoS',
   'Discussing sensitive matters in open',
   'Fallos en el DNS',
   'Dumpster diving',
   'Polvo/Arena',
   'Embezzlement',
   'Epidemic',
   'Extortion',
   'Fuego',
   'Inundación',
   'Fugas de Gas',
   'Fallo de Hardware',
   'Hazardous waste exposure',
   'Calor',
   'Vientos Fuertes',
   'Error Humano',
   'Huracán',
   'Falla HVAC',
   'Problemas Legales',
   'Dejar las pantallas expuestas o nobloqueadas',
   'Dejar las puertas sin seguro',
   'Dejar documentos sensitivos expuestos',
   'Rayo',
   'Perdida o Robo de laptops',
   'Código Malicioso',
   'Spoofing de Red',
   'Puertas Traseras en red/aplicaciones',
   'Bombas de Tiempo en Redes/aplicaciones',
   'Fallo de Energía',
   'Fluctuación de Poder',
   'Contaminación por Radiación',
   'Robo',
   'Sabotaje',
   'Actividad Sismica',
   'Shoulder surfing',
   'Tormentas de nieve/granizo',
   'Ingeniería Social',
   'Defectos de Software',
   'Solar flares',
   'Fallos del Sistema',
   'Tailgating to gain unauthorized access',
   'Ataque Terrorista',
   'Fallos en las Telecomunicaciones',
   'Tidal Wave',
   'Tornados',
   'Troyanos',
   'Tifón',
   'Acceso no autorizado a la red o al sistema',
   'Escaneos no Autorizados',
   'DDoS no Intencional',
   'Mala legislación no intencional',
   'Vandalismo',
   'Virus hoaxes',
   'Viruses',
   'Erupción Volcánica',
   'Guerra',
   'War dialing',
   'Web defacements',
   'Work stoppage/ strike',
   'Gusanos',       
];

